### ISSUE TITLE
404 error on export for section that is not available on a multisite

### ISSUE THREAD

**Issue by RobErskine** [la-haute-societe/craft-page-exporter#1]
Hey there. Thanks for this plugin; it's exactly what I need for the current project that I am working on.

I'm getting a 404 error when trying to export an entry from a structure called "Emails". I think I've diagnosed it down to the fact that the structure is only available on one site in my multisite setup.

![structure multisite settings](https://cl.ly/e46ed1021b60/Screen%20Shot%202019-06-19%20at%2012.22.49%20PM.jpg) 

It's worth noting that when I enable that second site and give it URLs, the export works great. However, I really don't want to have to make that particular structure available to each site. Is there a way to tell Page Exporter to only export based on the current site?

**Comment by maxime-colin** [comment]
I deployed a fix, could you please try again with the latest release (1.1.3) ?

**Comment by RobErskine** [comment]
Sorry for the delay on this. This looks good! Thanks for the fix. We've disabled our admin site and are able to export from the selected site just fine.
