### ISSUE TITLE
HTML Entities being converted to special characters on export

### ISSUE THREAD

**Issue by Chris-DuCharme** [la-haute-societe/craft-page-exporter#3]
Good morning,

I'm running into an issue where HTML Entities are being decoded into their special characters.

For example, if I use `&reg;` in my markup I would expect it to preserve the HTML Entity.  Instead I'm seeing the actual registration mark symbol "®" in the exported HTML. 

Since we are using this plugin to export HTML for emails, and a third party vendor is sending out the HTML we provide this is resulting in issues.

I'm finding that all special characters are displaying as a question mark inside a diamond when the email test blasts get sent out.  To resolve, we needing to go back through the exported HTML and manually change all the special characters back to HTML entities.  Nonbreaking spaces, `&nbsp;` are being converted into an invisible character that is being sanitized out during email test blasts resulting in no spaces.

Is there a way we can preserve the HTML entities on export and prevent them from being decoded back into their special symbols?

Thank you,
Chris

**Comment by maxime-colin** [comment]
I can't reproduce this problem locally. Can you check that:
- you use the latest version (1.1.5)
- all project files are encoded in UTF-8
- the doctype is specified

If you need to modify the generated HTML code, you can look at the config properties [assettransformers](https://github.com/la-haute-societe/craft-page-exporter#assettransformers).

**Comment by Chris-DuCharme** [comment]
Good morning @maxime-colin ,

Thanks for the reply.

We were on 1.1.3 but just upgraded to 1.1.5 and retested. 

All project files are encoded in UTF-8.

We are specifying the following doctype: `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`

Playing around with settings a little more we found the following.
Since these are emails we were defining UTF-8 like this: `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">` 

Using the HTML5 format, `<meta charset="UTF-8">`, resolves the issue.

We just need to do some testing to make sure changing the way UTF-8 is set doesn't cause any issues with any emails clients.

Thanks for you help.
