### ISSUE TITLE
Error installing plugin as part of deployment script

### ISSUE THREAD

**Issue by BillBushee** [la-haute-societe/craft-page-exporter#33]
Install failing on Craft 3.7.27.2 when using project config settings
PHP 7.3.27.2

When I run _php craft project-config/apply_ it attempts to install the plugin, and fails with the following error:

`Error: Calling unknown method: craft\console\Request::getParam()`
![project-config](https://user-images.githubusercontent.com/366423/153659282-4b9e349e-39f7-42ad-afe1-c873ae9816c6.png)

This can be traced to the Context service on line 30.

`$fromGetParam = (int)\Craft::$app->request->getParam('pageExporterContext') === 1;`

The **craft\web\request** class has a getParam method but the **craft\console\request** class does not. I assume this works when installing through the CMS, but when I attempt to install this through a deployment tool that runs install commands in a bash script it's failing.

**Comment by nstCactus** [comment]
Fixed by https://github.com/la-haute-societe/craft-page-exporter/commit/db1a032de9011930cb3698abaef6f5f47e1cc2b3.

Version 1.5.1 is out with that change.
